//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_student
    {
        [Required (ErrorMessage ="required")]
        public int ID { get; set; }

        [Required(ErrorMessage = "required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "required")]
        public string Fname { get; set; }

        [Required(ErrorMessage = "required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "required")]
        [MinLength(11,ErrorMessage ="Mobile number must be 11 digit")]
        public string Mobile { get; set; }

        [Required(ErrorMessage = "required")]
        public string Description { get; set; }
    }
}
